#!/usr/bin/env bash
# OPD v2 TEACHER /score server (hidden-state extraction -> shared FS) — in-container, Blackwell/B200.
# De-apptainer'd port of ycchen training/opd_v2/run_teacher_fs.sh:
#   * no `apptainer exec $SIF`; runs the image's serve venv
#   * the 4 teacher patches (deepseek_v4 / scheduler / output_processor / http_server out_path FS-write)
#     are BAKED into the venv at build time (generated by teacher_extract/_patch_sglang.py)
#   * TEACHER IS MLA (no attention sink) -> the triton-sink rule does NOT apply here.
#
# B200 TODO (flagged, not silently defaulted):
#   * `--moe-runner-backend marlin` is Ampere/Hopper int4; on Blackwell pick a supported MoE backend
#     (cutlass/triton/flashinfer) — benchmark. Override via MOE_BACKEND.
#   * MLA attention backend: set a Blackwell-capable one (flashinfer/triton) via ATTN_BACKEND if the
#     default isn't valid on sm_100.
#   * For an Olmo3 test-teacher instead of DeepSeek-V4-Flash, the hidden-extract patch differs
#     (olmo2_sink extraction, not deepseek_v4) — see OPD_V2_TRAIN_DOCKER_PLAN.md.
#
#   CUDA_VISIBLE_DEVICES=3 ./run_teacher.sh --tp 1 --port 8100
set -euo pipefail

# --- serve venv is CUDA-13 (sglang 0.5.14): use the CUDA-13 nvcc/CCCL for its runtime JIT kernels -----
# The base image defaults CUDA_HOME to cu128, but sglang JIT-compiles kernels (DeepSeek-V4 topk etc.)
# that use CUDA-13 cuda::ptx intrinsics -> point it at the CUDA-13 toolkit baked in the image (the
# base/trainer venv stays cu128).
export CUDA_HOME=/usr/local/cuda-13.0 CUDA_PATH=/usr/local/cuda-13.0
export PATH=/usr/local/cuda-13.0/bin:${PATH}

# --- CUDA-13 forward-compat (see Dockerfile cuda13compat stage) --------------------------------------
# sglang 0.5.14 is a CUDA-13 build and can't be pinned to cu128 (sgl-project/sglang#25069). If this
# node's driver predates CUDA 13, load the baked forward-compat libcuda so the serve stack runs on
# CUDA-12.x datacenter drivers (>=525). On a CUDA-13 driver this is skipped (native libcuda is used).
if [ -d /opt/cuda13-compat ]; then
  _cc=$(nvidia-smi 2>/dev/null | sed -n 's/.*CUDA Version: *\([0-9]\{1,\}\).*/\1/p' | head -1)
  if [ -n "${_cc}" ] && [ "${_cc}" -lt 13 ] 2>/dev/null; then
    export LD_LIBRARY_PATH="/opt/cuda13-compat:${LD_LIBRARY_PATH:-}"
    echo "[cuda13-compat] node driver CUDA ${_cc}.x < 13 -> forward-compat libcuda enabled" >&2
  fi
fi
SERVE_PY="${SERVE_PY:-/opt/venv/serve/bin/python}"
OPD_REPO="${OPD_REPO:-/opt/opd/repo}"
MODEL="${MODEL:-${DEEPSEEK_V4_FLASH:-/models/DeepSeek-V4-Flash}}"
TP="${TP:-4}"; PORT=8100
while [ $# -gt 0 ]; do case "$1" in --tp) TP="$2"; shift 2;; --port) PORT="$2"; shift 2;; *) shift;; esac; done

SPOOL="${SPOOL:-/dev/shm/opd-v2-teacher-spool}"; mkdir -p "$SPOOL"
# MoE backend: default "auto" -> sglang picks per hardware. On Hopper auto resolves to marlin (== her V33);
# on Blackwell/B200 it picks a supported backend. If auto's B200 pick misbehaves, override with
# MOE_BACKEND=flashinfer_mxfp4 (validated for DeepSeek-V4-Flash on GB200 — sglang issue #23743).
MOE_BACKEND="${MOE_BACKEND:-auto}"
ATTN_ARGS=(); [ -n "${ATTN_BACKEND:-}" ] && ATTN_ARGS+=(--attention-backend "$ATTN_BACKEND")
# B200: sglang #23743's FlashMLA mixed decode+multi-prefill crash — set MAX_PREFILL_TOKENS=8192 to avoid it.
PREFILL_ARGS=(); [ -n "${MAX_PREFILL_TOKENS:-}" ] && PREFILL_ARGS+=(--max-prefill-tokens "$MAX_PREFILL_TOKENS")
DIST_ARGS=()
[ -n "${DIST_INIT_ADDR:-}" ]  && DIST_ARGS+=(--dist-init-addr "$DIST_INIT_ADDR")
[ -n "${SGLANG_NCCL_PORT:-}" ] && DIST_ARGS+=(--nccl-port "$SGLANG_NCCL_PORT")

export SGLANG_DSV4_HIDDEN_POST_NORM=1 \
       SGLANG_JIT_DEEPGEMM_FAST_WARMUP=1 \
       SGLANG_OPT_FP8_WO_A_GEMM=0 \
       MALLOC_ARENA_MAX=4 \
       SGLANG_HIDDEN_SPOOL_DIR="$SPOOL" \
       SGLANG_HIDDEN_CODEC_DIR="$OPD_REPO/training/_common" \
       OPD_V2_SRC="$OPD_REPO/training/opd_v2/src" \
       OPD_TEACHER_MODEL_PATH="$MODEL" \
       OPD_SCORE_TOP1_CHUNK="${OPD_SCORE_TOP1_CHUNK:-1024}"

exec "$SERVE_PY" -m sglang.launch_server \
  --model-path "$MODEL" --tp-size "$TP" --host 0.0.0.0 --port "$PORT" \
  "${DIST_ARGS[@]}" "${ATTN_ARGS[@]}" "${PREFILL_ARGS[@]}" \
  --enable-return-hidden-states --disable-radix-cache \
  --chunked-prefill-size "${CHUNKED_PREFILL:-11264}" --mem-fraction-static "${MEMFRAC:-0.80}" \
  --max-running-requests "${MAXRUN:-128}" --disable-cuda-graph \
  --context-length "${TEACHER_CONTEXT_LEN:-${CONTEXT_LEN:-69632}}" \
  --moe-runner-backend "$MOE_BACKEND" \
  --watchdog-timeout 1800 --log-level info
