#!/usr/bin/env bash
# OPD v2 TEACHER /score server (hidden-state extraction -> shared FS) — in-container, Blackwell/B200.
# De-apptainer'd port of ycchen training/opd_v2/run_teacher_fs.sh:
#   * no `apptainer exec $SIF`; runs the image's serve venv
#   * the 4 teacher patches (deepseek_v4 / scheduler / output_processor / http_server out_path FS-write)
#     are BAKED into the venv at build time (generated by teacher_extract/_patch_sglang.py)
#   * TEACHER IS MLA (no attention sink) -> the triton-sink rule does NOT apply here.
#
# B200 TODO (flagged, not silently defaulted):
#   * `--moe-runner-backend marlin` is Ampere/Hopper int4; on Blackwell pick a supported MoE backend
#     (cutlass/triton/flashinfer) — benchmark. Override via MOE_BACKEND.
#   * MLA attention backend: set a Blackwell-capable one (flashinfer/triton) via ATTN_BACKEND if the
#     default isn't valid on sm_100.
#   * For an Olmo3 test-teacher instead of DeepSeek-V4-Flash, the hidden-extract patch differs
#     (olmo2_sink extraction, not deepseek_v4) — see OPD_V2_TRAIN_DOCKER_PLAN.md.
#
#   CUDA_VISIBLE_DEVICES=3 ./run_teacher.sh --tp 1 --port 8100
set -euo pipefail
SERVE_PY="${SERVE_PY:-/opt/venv/serve/bin/python}"
OPD_REPO="${OPD_REPO:-/opt/opd/repo}"
MODEL="${MODEL:-${DEEPSEEK_V4_FLASH:-/models/DeepSeek-V4-Flash}}"
TP="${TP:-4}"; PORT=8100
while [ $# -gt 0 ]; do case "$1" in --tp) TP="$2"; shift 2;; --port) PORT="$2"; shift 2;; *) shift;; esac; done

SPOOL="${SPOOL:-/dev/shm/opd-v2-teacher-spool}"; mkdir -p "$SPOOL"
MOE_BACKEND="${MOE_BACKEND:-marlin}"      # B200: switch to a Blackwell MoE backend
ATTN_ARGS=(); [ -n "${ATTN_BACKEND:-}" ] && ATTN_ARGS+=(--attention-backend "$ATTN_BACKEND")
DIST_ARGS=()
[ -n "${DIST_INIT_ADDR:-}" ]  && DIST_ARGS+=(--dist-init-addr "$DIST_INIT_ADDR")
[ -n "${SGLANG_NCCL_PORT:-}" ] && DIST_ARGS+=(--nccl-port "$SGLANG_NCCL_PORT")

export SGLANG_DSV4_HIDDEN_POST_NORM=1 \
       SGLANG_JIT_DEEPGEMM_FAST_WARMUP=1 \
       SGLANG_OPT_FP8_WO_A_GEMM=0 \
       MALLOC_ARENA_MAX=4 \
       SGLANG_HIDDEN_SPOOL_DIR="$SPOOL" \
       SGLANG_HIDDEN_CODEC_DIR="$OPD_REPO/training/_common" \
       OPD_V2_SRC="$OPD_REPO/training/opd_v2/src" \
       OPD_TEACHER_MODEL_PATH="$MODEL" \
       OPD_SCORE_TOP1_CHUNK="${OPD_SCORE_TOP1_CHUNK:-1024}"

exec "$SERVE_PY" -m sglang.launch_server \
  --model-path "$MODEL" --tp-size "$TP" --host 0.0.0.0 --port "$PORT" \
  "${DIST_ARGS[@]}" "${ATTN_ARGS[@]}" \
  --enable-return-hidden-states --disable-radix-cache \
  --chunked-prefill-size "${CHUNKED_PREFILL:-11264}" --mem-fraction-static "${MEMFRAC:-0.80}" \
  --max-running-requests "${MAXRUN:-128}" --disable-cuda-graph \
  --context-length "${TEACHER_CONTEXT_LEN:-${CONTEXT_LEN:-69632}}" \
  --moe-runner-backend "$MOE_BACKEND" \
  --watchdog-timeout 1800 --log-level info
